import type { Metadata } from "next"
import { GeistMono } from "geist/font/mono"
import "./globals.css"
import { Toaster } from "sonner"
import Footer from "./_components/footer"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${GeistMono.variable} antialiased`}>
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  )
}
